//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chiptuning_Company_V7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string Vin { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public string Displacement { get; set; }
        public string Fuel { get; set; }
        public string Power { get; set; }
        public Nullable<int> Owner { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
